name: mytodo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  date_picker_timeline: ^1.2.5
  flutter_slidable: ^3.1.0
  firebase_core: ^2.28.0
  cloud_firestore: ^4.16.0

  flutter_localizations:
    sdk: flutter
  intl_utils: ^2.8.7
  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  generate: true
  assets:
    - assets/images/


  uses-material-design: true


